### ISSUE TITLE
Using CentOS 8 with kitchen fails

### ISSUE THREAD

**Issue by rishichawda** [test-kitchen/dokken-images#33]
_I'm new to kitchen so please let me know if other details are required If I have missed any._ 

## Brief Description

On running `kitchen converge` with `dokken/centos-8` image, it fails with error
```
sh: /opt/kitchen/run_command: No such file or directory
```

![error](https://user-images.githubusercontent.com/26366288/94799782-4e4bc900-0401-11eb-926f-794342b98f0f.png)

## Version

Test Kitchen version: 2.6.0

## Environment

OS: macOS Catalina (10.15.5)

kitchen.yml

```yaml
---
driver:
  name: dokken

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
  - name: ubuntu-20.04
  - name: centos-8
    driver:
      image: dokken/centos-8

suites:
  - name: default
    provisioner:
      policyfile_path: policy.rb
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:

```

## Scenario

Running converge for centos

## Steps to Reproduce

Run `kitchen converge` with the centos 8 image

## Expected Result

Should be able to successfully converge.
## :heavy_plus_sign: Additional context

No issues with CentOS 7 image so my guess is something is wrong with the image rather than test-kitchen.

**Comment by tas50** [comment]
Can you delete the image you have on your system and try again. We use this image in cookbook testing and testing of chef itself without any issues.

**Comment by tas50** [comment]
Closing this one out since we never heard back

**Comment by mateuszkwiatkowski** [comment]
Hello,
I'm seeing the same issue. It only happens when kitchen is run by Gitlab CI (so docker-in-docker), it works fine on local workstations (both Linux and Docker on Mac).

.kitchen.yml:

```YAML
---
driver:
  name: dokken
  privileged: true # required for systemd
  chef_version: 16.9.32

transport:
   name: dokken

provisioner:
  chef_license: accept
  name: dokken

verifier:
  name: inspec

platforms:
- name: ubuntu-20.04
  driver:
    image: dokken/ubuntu-20.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

suites:
  - name: default
    run_list:
    - recipe[base]
    attributes: {'kitchen': true}
```

Log:

```
$ bundle exec kitchen test default-ubuntu-2004
-----> Starting Test Kitchen (v2.10.0)
-----> Cleaning up any prior instances of <default-ubuntu-2004>
-----> Destroying <default-ubuntu-2004>...
       Deleting kitchen sandbox at /root/.dokken/kitchen_sandbox/894ab4d1c1-default-ubuntu-2004
       Deleting verifier sandbox at /root/.dokken/verifier_sandbox/894ab4d1c1-default-ubuntu-2004
       Finished destroying <default-ubuntu-2004> (0m0.03s).
-----> Testing <default-ubuntu-2004>
-----> Creating <default-ubuntu-2004>...
       Creating kitchen sandbox at /root/.dokken/kitchen_sandbox/894ab4d1c1-default-ubuntu-2004
       Creating verifier sandbox at /root/.dokken/verifier_sandbox/894ab4d1c1-default-ubuntu-2004
       Building work image..
       Finished creating <default-ubuntu-2004> (0m51.80s).
-----> Converging <default-ubuntu-2004>...
       Persisting a license for Chef Infra Client at path /etc/chef/accepted_licenses/chef_infra_client
       Persisting a license for Chef InSpec at path /etc/chef/accepted_licenses/inspec
+---------------------------------------------+
✔ 2 product licenses accepted.
+---------------------------------------------+
       Creating kitchen sandbox in /root/.dokken/kitchen_sandbox/894ab4d1c1-default-ubuntu-2004
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 7.1.0...
       Removing non-cookbook files before transfer
       Preparing data_bags
       Preparing validation.pem
       Preparing client.rb
sh: 0: Can't open /opt/kitchen/run_command
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-ubuntu-2004>.  Please see .kitchen/logs/default-ubuntu-2004.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
